# baseURL
@baseURL = http://localhost:3000

###
# Find All Users
GET {{ baseURL }}/users
Cookie: Authorization=admin_user_token

###
# Find User By Id
GET {{ baseURL }}/users/1
Cookie: Authorization=admin_user_token

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json
Cookie: Authorization=admin_only_token

{
    "username": "username",
    "password": "password"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/1
Content-Type: application/json
Cookie: Authorization=admin_only_token

{
    "username": "username",
    "password": "password"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/1
Cookie: Authorization=admin_only_token
